name: Playwright Tests – Grafana Cloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test
        continue-on-error: true

      - name: Push metrics to Grafana Cloud
        if: always() # Ensures metrics are sent even if tests fail
        env:
          # Matching variables to the script logic
          GRAFANA_URL: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push
          GRAFANA_USER: ${{ secrets.GRAFANA_INSTANCE_ID }}
          GRAFANA_TOKEN: ${{ secrets.GRAFANA_TOKEN }}
        run: node scripts/push-metrics.js

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30